name: CI/CD - Trackr - Railway

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

    #   - name: Rodar testes
    #     run: npm test

      - name: Build do projeto
        run: npm run build

#   deploy:
#     needs: build-and-test
#     runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true

#     steps:
#       - name: Checkout codigo
#         uses: actions/checkout@v4

#       - name: Instalar Railway CLI
#         run: npm i -g @railway/cli

#       - name: Deploy para Railway
#         run: railway up
#         env:
#           RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}